/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package job04;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.collections.ObservableList; 
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;
import javafx.geometry.Insets; 
import javafx.geometry.Pos;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        
        FlowPane flowPane = new FlowPane();
        TextField textField = new TextField ();


        Button btn = new Button();
        btn.setText("Envoyer");
        btn.setOnAction((ActionEvent event) -> {
            String name = textField.getText();
            System.out.println(name);
        });
        Label l = new Label("Nom :");
        l.setStyle("-fx-font-size: 40; -fx-text-fill: linear-gradient(from 0% 0% to 100% 200%, repeat, aqua 0%, red 50%); -fx-font-weight: BOLD;");
        flowPane.setHgap(25);
        flowPane.setMargin(l, new Insets(20, 20, 20, 20)); 
        ObservableList list = flowPane.getChildren(); 
        //Adding all the nodes to the flow pane 
        list.addAll(l,textField, btn); 
        flowPane.setStyle("-fx-background-color: ORANGE;"); 
        Scene scene = new Scene(flowPane, 640, 480);
        
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}