/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package job06;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.collections.ObservableList; 
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;
import javafx.geometry.Insets; 
import javafx.geometry.Pos;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        
        FlowPane flowPane = new FlowPane();
        ComboBox comboBox1 = new ComboBox<>();
        ComboBox comboBox2 = new ComboBox<>();
        ObservableList<String> list = FXCollections.observableArrayList();
        ObservableList<String> list_colors = FXCollections.observableArrayList();;
        list.addAll("test","allo");
        list_colors.addAll("orange","jaune","vert");

        comboBox1.setItems(list);
        comboBox2.setItems(list_colors);

        Button btn = new Button();
        btn.setText("Ok");
        btn.setOnAction((ActionEvent event) -> {
            System.out.println(comboBox1.getValue()+" "+comboBox2.getValue());
        });
        Label l = new Label("Nom :");
        l.setStyle("-fx-font-size: 40; -fx-text-fill: linear-gradient(from 0% 0% to 100% 200%, repeat, aqua 0%, red 50%); -fx-font-weight: BOLD;");
        flowPane.setHgap(25);
        flowPane.setMargin(l, new Insets(20, 20, 20, 20)); 
        ObservableList listing = flowPane.getChildren(); 
        //Adding all the nodes to the flow pane 
        listing.addAll(l,comboBox1, comboBox2,btn); 
        Scene scene = new Scene(flowPane, 640, 480);
        
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}